INSERT INTO characters (name, alias, alignment, powers, image_url) VALUES
('Spider-Man', 'Peter Parker', 'hero', 'Superhuman strength, agility, and spider-sense', 'https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png'),
('Loki', 'Loki Laufeyson', 'villain', 'Magic, shape-shifting, skilled sorcerer', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Various_incarnations_of_Loki_%282014%29.webp/256px-Various_incarnations_of_Loki_%282014%29.webp.png'),
('Hulk', 'Bruce Banner', 'hero', 'Superhuman strength, regeneration, and durability', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/Hulk_%28circa_2019%29.png/220px-Hulk_%28circa_2019%29.png'),
('Thanos', 'Thanos', 'villain', 'Superhuman strength, telepathy, and use of the Infinity Gauntlet', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Thanos_Infinity_4.png/220px-Thanos_Infinity_4.png'),
('Iron Man', 'Tony Stark', 'hero', 'Genius-level intellect, expert engineer, powered armor suit', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Iron_Man_%28circa_2018%29.png/220px-Iron_Man_%28circa_2018%29.png'),
('Green Goblin', 'Norman Osborn', 'villain', 'Genius intellect, enhanced strength, and glider', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Green_Goblin_Comic_Art_by_Luke_Ross.webp/220px-Green_Goblin_Comic_Art_by_Luke_Ross.webp.png'),
('Black Widow', 'Natasha Romanoff', 'hero', 'Expert martial artist, acrobat, espionage', 'https://upload.wikimedia.org/wikipedia/en/1/1b/Black_Widow_1.png'),
('Doctor Octopus', 'Otto Octavius', 'villain', 'Mechanical tentacles, genius-level intellect', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Dr._Octopus_Marvel.jpg/220px-Dr._Octopus_Marvel.jpg'),
('Thor', 'Thor Odinson', 'hero', 'Superhuman strength, weather manipulation, skilled warrior', 'https://upload.wikimedia.org/wikipedia/en/1/17/Thor_by_Olivier_Coipel.png'),
('Magneto', 'Erik Lensherr', 'villain', 'Magnetism control, superhuman strength', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Magneto_%28Marvel_Comics_character%29.jpg/220px-Magneto_%28Marvel_Comics_character%29.jpg');